// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"bld-backend/apps/ordersapi/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/healthz",
				Handler: HealthzHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/ordersapi/v1/spot/orders",
				Handler: CreateSpotOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/ordersapi/v1/spot/orders/cancel",
				Handler: CancelSpotOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/ordersapi/v1/spot/orders",
				Handler: ListSpotOrdersHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/ordersapi/v1/spot/trades",
				Handler: ListSpotTradesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/ordersapi/v1/spot/markets",
				Handler: ListSpotMarketsHandler(serverCtx),
			},
		},
	)
}
