// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"bld-backend/apps/gatewayapi/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

// 注册路由
func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/healthz",
				Handler: HealthzHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/deposit/address",
				Handler: GetDepositAddressHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/withdraw",
				Handler: WithdrawHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/wallet/sweep/hot",
				Handler: SweepToHotHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/wallet/create",
				Handler: CreateWalletHandler(serverCtx),
			},
		},
	)
}
