/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace BloomMarketplace {
      
    export type ListingStruct = {nft: AddressLike, seller: AddressLike, tokenId: BigNumberish, price: BigNumberish, deadline: BigNumberish, salt: BigNumberish}

    export type ListingStructOutput = [nft: string, seller: string, tokenId: bigint, price: bigint, deadline: bigint, salt: bigint] & {nft: string, seller: string, tokenId: bigint, price: bigint, deadline: bigint, salt: bigint }
  

    export type BidStruct = {nft: AddressLike, buyer: AddressLike, tokenId: BigNumberish, price: BigNumberish, deadline: BigNumberish, salt: BigNumberish}

    export type BidStructOutput = [nft: string, buyer: string, tokenId: bigint, price: bigint, deadline: bigint, salt: bigint] & {nft: string, buyer: string, tokenId: bigint, price: bigint, deadline: bigint, salt: bigint }
  
    }

  export interface BloomMarketplaceInterface extends Interface {
    getFunction(nameOrSignature: "acceptBid" | "buy" | "buyBatch" | "cancelBidOrder" | "cancelListingOrder" | "eip712Domain" | "feePrecision" | "feeRate" | "minNonce" | "orderInvalidated" | "owner" | "renounceOwnership" | "setFeeRate" | "token" | "transferOwnership" | "updateMinNonce" | "withdraw" | "withdrawFees"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BidAccepted" | "Buy" | "EIP712DomainChanged" | "FeesWithdrawn" | "MinNonceUpdated" | "OrderCancelled" | "OwnershipTransferred" | "Withdraw"): EventFragment;

    encodeFunctionData(functionFragment: 'acceptBid', values: [BloomMarketplace.ListingStruct, BytesLike, BytesLike[], BytesLike, BigNumberish, BytesLike, BloomMarketplace.BidStruct, BytesLike]): string;
encodeFunctionData(functionFragment: 'buy', values: [BloomMarketplace.ListingStruct, BytesLike, BytesLike[], BytesLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'buyBatch', values: [BloomMarketplace.ListingStruct[], BytesLike[], BytesLike[][], BytesLike[], BigNumberish[], BytesLike[]]): string;
encodeFunctionData(functionFragment: 'cancelBidOrder', values: [BloomMarketplace.BidStruct]): string;
encodeFunctionData(functionFragment: 'cancelListingOrder', values: [BloomMarketplace.ListingStruct]): string;
encodeFunctionData(functionFragment: 'eip712Domain', values?: undefined): string;
encodeFunctionData(functionFragment: 'feePrecision', values?: undefined): string;
encodeFunctionData(functionFragment: 'feeRate', values?: undefined): string;
encodeFunctionData(functionFragment: 'minNonce', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'orderInvalidated', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setFeeRate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateMinNonce', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawFees', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'acceptBid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelBidOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelListingOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'eip712Domain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feePrecision', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minNonce', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'orderInvalidated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFeeRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateMinNonce', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFees', data: BytesLike): Result;
  }

  
    export namespace BidAcceptedEvent {
      export type InputTuple = [listingHash: BytesLike, bidHash: BytesLike, seller: AddressLike, buyer: AddressLike, nft: AddressLike, tokenId: BigNumberish, price: BigNumberish, fee: BigNumberish];
      export type OutputTuple = [listingHash: string, bidHash: string, seller: string, buyer: string, nft: string, tokenId: bigint, price: bigint, fee: bigint];
      export interface OutputObject {listingHash: string, bidHash: string, seller: string, buyer: string, nft: string, tokenId: bigint, price: bigint, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BuyEvent {
      export type InputTuple = [listingHash: BytesLike, seller: AddressLike, buyer: AddressLike, nft: AddressLike, tokenId: BigNumberish, price: BigNumberish, fee: BigNumberish];
      export type OutputTuple = [listingHash: string, seller: string, buyer: string, nft: string, tokenId: bigint, price: bigint, fee: bigint];
      export interface OutputObject {listingHash: string, seller: string, buyer: string, nft: string, tokenId: bigint, price: bigint, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EIP712DomainChangedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeesWithdrawnEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint];
      export interface OutputObject {to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MinNonceUpdatedEvent {
      export type InputTuple = [maker: AddressLike, newMinNonce: BigNumberish];
      export type OutputTuple = [maker: string, newMinNonce: bigint];
      export interface OutputObject {maker: string, newMinNonce: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderCancelledEvent {
      export type InputTuple = [orderHash: BytesLike, maker: AddressLike, isListing: boolean];
      export type OutputTuple = [orderHash: string, maker: string, isListing: boolean];
      export interface OutputObject {orderHash: string, maker: string, isListing: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawEvent {
      export type InputTuple = [sender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [sender: string, amount: bigint];
      export interface OutputObject {sender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BloomMarketplace extends BaseContract {
    
    connect(runner?: ContractRunner | null): BloomMarketplace;
    waitForDeployment(): Promise<this>;

    interface: BloomMarketplaceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    acceptBid: TypedContractMethod<
      [listing: BloomMarketplace.ListingStruct, listingSignature: BytesLike, proof: BytesLike[], merkleRoot: BytesLike, rootDeadline: BigNumberish, batchSignature: BytesLike, bid: BloomMarketplace.BidStruct, bidSignature: BytesLike, ],
      [[string, string] & {listingHash: string, bidHash: string }],
      'nonpayable'
    >
    

    
    buy: TypedContractMethod<
      [listing: BloomMarketplace.ListingStruct, listingSignature: BytesLike, proof: BytesLike[], merkleRoot: BytesLike, rootDeadline: BigNumberish, batchSignature: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    buyBatch: TypedContractMethod<
      [listings: BloomMarketplace.ListingStruct[], listingSignatures: BytesLike[], proofs: BytesLike[][], merkleRoots: BytesLike[], rootDeadlines: BigNumberish[], batchSignatures: BytesLike[], ],
      [string[]],
      'nonpayable'
    >
    

    
    cancelBidOrder: TypedContractMethod<
      [bid: BloomMarketplace.BidStruct, ],
      [string],
      'nonpayable'
    >
    

    
    cancelListingOrder: TypedContractMethod<
      [listing: BloomMarketplace.ListingStruct, ],
      [string],
      'nonpayable'
    >
    

    
    eip712Domain: TypedContractMethod<
      [],
      [[string, string, string, bigint, string, string, bigint[]] & {fields: string, name: string, version: string, chainId: bigint, verifyingContract: string, salt: string, extensions: bigint[] }],
      'view'
    >
    

    
    feePrecision: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    feeRate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    minNonce: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    orderInvalidated: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setFeeRate: TypedContractMethod<
      [_feeRate: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateMinNonce: TypedContractMethod<
      [newMinNonce: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    withdrawFees: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'acceptBid'): TypedContractMethod<
      [listing: BloomMarketplace.ListingStruct, listingSignature: BytesLike, proof: BytesLike[], merkleRoot: BytesLike, rootDeadline: BigNumberish, batchSignature: BytesLike, bid: BloomMarketplace.BidStruct, bidSignature: BytesLike, ],
      [[string, string] & {listingHash: string, bidHash: string }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'buy'): TypedContractMethod<
      [listing: BloomMarketplace.ListingStruct, listingSignature: BytesLike, proof: BytesLike[], merkleRoot: BytesLike, rootDeadline: BigNumberish, batchSignature: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'buyBatch'): TypedContractMethod<
      [listings: BloomMarketplace.ListingStruct[], listingSignatures: BytesLike[], proofs: BytesLike[][], merkleRoots: BytesLike[], rootDeadlines: BigNumberish[], batchSignatures: BytesLike[], ],
      [string[]],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelBidOrder'): TypedContractMethod<
      [bid: BloomMarketplace.BidStruct, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelListingOrder'): TypedContractMethod<
      [listing: BloomMarketplace.ListingStruct, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'eip712Domain'): TypedContractMethod<
      [],
      [[string, string, string, bigint, string, string, bigint[]] & {fields: string, name: string, version: string, chainId: bigint, verifyingContract: string, salt: string, extensions: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'feePrecision'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'feeRate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'minNonce'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'orderInvalidated'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFeeRate'): TypedContractMethod<
      [_feeRate: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateMinNonce'): TypedContractMethod<
      [newMinNonce: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawFees'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BidAccepted'): TypedContractEvent<BidAcceptedEvent.InputTuple, BidAcceptedEvent.OutputTuple, BidAcceptedEvent.OutputObject>;
getEvent(key: 'Buy'): TypedContractEvent<BuyEvent.InputTuple, BuyEvent.OutputTuple, BuyEvent.OutputObject>;
getEvent(key: 'EIP712DomainChanged'): TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
getEvent(key: 'FeesWithdrawn'): TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
getEvent(key: 'MinNonceUpdated'): TypedContractEvent<MinNonceUpdatedEvent.InputTuple, MinNonceUpdatedEvent.OutputTuple, MinNonceUpdatedEvent.OutputObject>;
getEvent(key: 'OrderCancelled'): TypedContractEvent<OrderCancelledEvent.InputTuple, OrderCancelledEvent.OutputTuple, OrderCancelledEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Withdraw'): TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;

    filters: {
      
      'BidAccepted(bytes32,bytes32,address,address,address,uint256,uint256,uint256)': TypedContractEvent<BidAcceptedEvent.InputTuple, BidAcceptedEvent.OutputTuple, BidAcceptedEvent.OutputObject>;
      BidAccepted: TypedContractEvent<BidAcceptedEvent.InputTuple, BidAcceptedEvent.OutputTuple, BidAcceptedEvent.OutputObject>;
    

      'Buy(bytes32,address,address,address,uint256,uint256,uint256)': TypedContractEvent<BuyEvent.InputTuple, BuyEvent.OutputTuple, BuyEvent.OutputObject>;
      Buy: TypedContractEvent<BuyEvent.InputTuple, BuyEvent.OutputTuple, BuyEvent.OutputObject>;
    

      'EIP712DomainChanged()': TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
      EIP712DomainChanged: TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
    

      'FeesWithdrawn(address,uint256)': TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
      FeesWithdrawn: TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
    

      'MinNonceUpdated(address,uint256)': TypedContractEvent<MinNonceUpdatedEvent.InputTuple, MinNonceUpdatedEvent.OutputTuple, MinNonceUpdatedEvent.OutputObject>;
      MinNonceUpdated: TypedContractEvent<MinNonceUpdatedEvent.InputTuple, MinNonceUpdatedEvent.OutputTuple, MinNonceUpdatedEvent.OutputObject>;
    

      'OrderCancelled(bytes32,address,bool)': TypedContractEvent<OrderCancelledEvent.InputTuple, OrderCancelledEvent.OutputTuple, OrderCancelledEvent.OutputObject>;
      OrderCancelled: TypedContractEvent<OrderCancelledEvent.InputTuple, OrderCancelledEvent.OutputTuple, OrderCancelledEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Withdraw(address,uint256)': TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
      Withdraw: TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
    
    };
  }