/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { USDT } from './USDT.js';
export * as factories from './factories/index.js';
export { USDT__factory } from './factories/USDT__factory.js';