// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.6
// source: wallet.proto

package walletpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAssetsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 0 表示该用户下全部资产；>0 时仅返回该 asset_id。
	AssetId       int32 `protobuf:"varint,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetsRequest) Reset() {
	*x = GetAssetsRequest{}
	mi := &file_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetsRequest) ProtoMessage() {}

func (x *GetAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetsRequest.ProtoReflect.Descriptor instead.
func (*GetAssetsRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *GetAssetsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetAssetsRequest) GetAssetId() int32 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

// AssetItem 资产项
type AssetItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Symbol           string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	AssetId          int32                  `protobuf:"varint,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,3,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	FrozenBalance    string                 `protobuf:"bytes,4,opt,name=frozen_balance,json=frozenBalance,proto3" json:"frozen_balance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AssetItem) Reset() {
	*x = AssetItem{}
	mi := &file_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetItem) ProtoMessage() {}

func (x *AssetItem) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetItem.ProtoReflect.Descriptor instead.
func (*AssetItem) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *AssetItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AssetItem) GetAssetId() int32 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

func (x *AssetItem) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *AssetItem) GetFrozenBalance() string {
	if x != nil {
		return x.FrozenBalance
	}
	return ""
}

// GetAssetsResponse 获取资产响应
type GetAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*AssetItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetsResponse) Reset() {
	*x = GetAssetsResponse{}
	mi := &file_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetsResponse) ProtoMessage() {}

func (x *GetAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetsResponse.ProtoReflect.Descriptor instead.
func (*GetAssetsResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *GetAssetsResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetAssetsResponse) GetItems() []*AssetItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// FreezeForOrderRequest 冻结资产请求
type FreezeForOrderRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	UserId  uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssetId int32                  `protobuf:"varint,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	OrderId uint64                 `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount  string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"` // 正数十进制字符串
	// 与库表一致：SPOT / CONTRACT
	TradingType   string `protobuf:"bytes,5,opt,name=trading_type,json=tradingType,proto3" json:"trading_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreezeForOrderRequest) Reset() {
	*x = FreezeForOrderRequest{}
	mi := &file_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeForOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeForOrderRequest) ProtoMessage() {}

func (x *FreezeForOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeForOrderRequest.ProtoReflect.Descriptor instead.
func (*FreezeForOrderRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *FreezeForOrderRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FreezeForOrderRequest) GetAssetId() int32 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

func (x *FreezeForOrderRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *FreezeForOrderRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *FreezeForOrderRequest) GetTradingType() string {
	if x != nil {
		return x.TradingType
	}
	return ""
}

// FreezeForOrderResponse 冻结资产响应
type FreezeForOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FreezeId      uint64                 `protobuf:"varint,1,opt,name=freeze_id,json=freezeId,proto3" json:"freeze_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreezeForOrderResponse) Reset() {
	*x = FreezeForOrderResponse{}
	mi := &file_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeForOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeForOrderResponse) ProtoMessage() {}

func (x *FreezeForOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeForOrderResponse.ProtoReflect.Descriptor instead.
func (*FreezeForOrderResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *FreezeForOrderResponse) GetFreezeId() uint64 {
	if x != nil {
		return x.FreezeId
	}
	return 0
}

// UnfreezeForOrderRequest 解冻资产请求
type UnfreezeForOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssetId       int32                  `protobuf:"varint,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	OrderId       uint64                 `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TradingType   string                 `protobuf:"bytes,4,opt,name=trading_type,json=tradingType,proto3" json:"trading_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfreezeForOrderRequest) Reset() {
	*x = UnfreezeForOrderRequest{}
	mi := &file_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfreezeForOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfreezeForOrderRequest) ProtoMessage() {}

func (x *UnfreezeForOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfreezeForOrderRequest.ProtoReflect.Descriptor instead.
func (*UnfreezeForOrderRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *UnfreezeForOrderRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnfreezeForOrderRequest) GetAssetId() int32 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

func (x *UnfreezeForOrderRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *UnfreezeForOrderRequest) GetTradingType() string {
	if x != nil {
		return x.TradingType
	}
	return ""
}

// UnfreezeForOrderResponse 解冻资产响应
type UnfreezeForOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfreezeForOrderResponse) Reset() {
	*x = UnfreezeForOrderResponse{}
	mi := &file_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfreezeForOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfreezeForOrderResponse) ProtoMessage() {}

func (x *UnfreezeForOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfreezeForOrderResponse.ProtoReflect.Descriptor instead.
func (*UnfreezeForOrderResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{6}
}

// ApplySpotTradeRequest 单笔现货成交结算（与 spot_trades 一行对应）。
type ApplySpotTradeRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	TradeId      uint64                 `protobuf:"varint,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	MarketId     int32                  `protobuf:"varint,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	BaseAssetId  int32                  `protobuf:"varint,3,opt,name=base_asset_id,json=baseAssetId,proto3" json:"base_asset_id,omitempty"`
	QuoteAssetId int32                  `protobuf:"varint,4,opt,name=quote_asset_id,json=quoteAssetId,proto3" json:"quote_asset_id,omitempty"`
	MakerOrderId uint64                 `protobuf:"varint,5,opt,name=maker_order_id,json=makerOrderId,proto3" json:"maker_order_id,omitempty"`
	TakerOrderId uint64                 `protobuf:"varint,6,opt,name=taker_order_id,json=takerOrderId,proto3" json:"taker_order_id,omitempty"`
	MakerUserId  uint64                 `protobuf:"varint,7,opt,name=maker_user_id,json=makerUserId,proto3" json:"maker_user_id,omitempty"`
	TakerUserId  uint64                 `protobuf:"varint,8,opt,name=taker_user_id,json=takerUserId,proto3" json:"taker_user_id,omitempty"`
	// 吃单方方向：BUY 或 SELL（与 spot_orders.side 一致）
	TakerSide     string `protobuf:"bytes,9,opt,name=taker_side,json=takerSide,proto3" json:"taker_side,omitempty"`
	Price         string `protobuf:"bytes,10,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string `protobuf:"bytes,11,opt,name=quantity,proto3" json:"quantity,omitempty"`
	MakerFee      string `protobuf:"bytes,12,opt,name=maker_fee,json=makerFee,proto3" json:"maker_fee,omitempty"` // 报价币
	TakerFee      string `protobuf:"bytes,13,opt,name=taker_fee,json=takerFee,proto3" json:"taker_fee,omitempty"` // 报价币
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplySpotTradeRequest) Reset() {
	*x = ApplySpotTradeRequest{}
	mi := &file_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplySpotTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplySpotTradeRequest) ProtoMessage() {}

func (x *ApplySpotTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplySpotTradeRequest.ProtoReflect.Descriptor instead.
func (*ApplySpotTradeRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *ApplySpotTradeRequest) GetTradeId() uint64 {
	if x != nil {
		return x.TradeId
	}
	return 0
}

func (x *ApplySpotTradeRequest) GetMarketId() int32 {
	if x != nil {
		return x.MarketId
	}
	return 0
}

func (x *ApplySpotTradeRequest) GetBaseAssetId() int32 {
	if x != nil {
		return x.BaseAssetId
	}
	return 0
}

func (x *ApplySpotTradeRequest) GetQuoteAssetId() int32 {
	if x != nil {
		return x.QuoteAssetId
	}
	return 0
}

func (x *ApplySpotTradeRequest) GetMakerOrderId() uint64 {
	if x != nil {
		return x.MakerOrderId
	}
	return 0
}

func (x *ApplySpotTradeRequest) GetTakerOrderId() uint64 {
	if x != nil {
		return x.TakerOrderId
	}
	return 0
}

func (x *ApplySpotTradeRequest) GetMakerUserId() uint64 {
	if x != nil {
		return x.MakerUserId
	}
	return 0
}

func (x *ApplySpotTradeRequest) GetTakerUserId() uint64 {
	if x != nil {
		return x.TakerUserId
	}
	return 0
}

func (x *ApplySpotTradeRequest) GetTakerSide() string {
	if x != nil {
		return x.TakerSide
	}
	return ""
}

func (x *ApplySpotTradeRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *ApplySpotTradeRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *ApplySpotTradeRequest) GetMakerFee() string {
	if x != nil {
		return x.MakerFee
	}
	return ""
}

func (x *ApplySpotTradeRequest) GetTakerFee() string {
	if x != nil {
		return x.TakerFee
	}
	return ""
}

type ApplySpotTradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplySpotTradeResponse) Reset() {
	*x = ApplySpotTradeResponse{}
	mi := &file_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplySpotTradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplySpotTradeResponse) ProtoMessage() {}

func (x *ApplySpotTradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplySpotTradeResponse.ProtoReflect.Descriptor instead.
func (*ApplySpotTradeResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{8}
}

var File_wallet_proto protoreflect.FileDescriptor

const file_wallet_proto_rawDesc = "" +
	"\n" +
	"\fwallet.proto\x12\bwalletpb\"F\n" +
	"\x10GetAssetsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\x05R\aassetId\"\x92\x01\n" +
	"\tAssetItem\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\x05R\aassetId\x12+\n" +
	"\x11available_balance\x18\x03 \x01(\tR\x10availableBalance\x12%\n" +
	"\x0efrozen_balance\x18\x04 \x01(\tR\rfrozenBalance\"W\n" +
	"\x11GetAssetsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12)\n" +
	"\x05items\x18\x02 \x03(\v2\x13.walletpb.AssetItemR\x05items\"\xa1\x01\n" +
	"\x15FreezeForOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\x05R\aassetId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x04R\aorderId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12!\n" +
	"\ftrading_type\x18\x05 \x01(\tR\vtradingType\"5\n" +
	"\x16FreezeForOrderResponse\x12\x1b\n" +
	"\tfreeze_id\x18\x01 \x01(\x04R\bfreezeId\"\x8b\x01\n" +
	"\x17UnfreezeForOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\x05R\aassetId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x04R\aorderId\x12!\n" +
	"\ftrading_type\x18\x04 \x01(\tR\vtradingType\"\x1a\n" +
	"\x18UnfreezeForOrderResponse\"\xb8\x03\n" +
	"\x15ApplySpotTradeRequest\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\x04R\atradeId\x12\x1b\n" +
	"\tmarket_id\x18\x02 \x01(\x05R\bmarketId\x12\"\n" +
	"\rbase_asset_id\x18\x03 \x01(\x05R\vbaseAssetId\x12$\n" +
	"\x0equote_asset_id\x18\x04 \x01(\x05R\fquoteAssetId\x12$\n" +
	"\x0emaker_order_id\x18\x05 \x01(\x04R\fmakerOrderId\x12$\n" +
	"\x0etaker_order_id\x18\x06 \x01(\x04R\ftakerOrderId\x12\"\n" +
	"\rmaker_user_id\x18\a \x01(\x04R\vmakerUserId\x12\"\n" +
	"\rtaker_user_id\x18\b \x01(\x04R\vtakerUserId\x12\x1d\n" +
	"\n" +
	"taker_side\x18\t \x01(\tR\ttakerSide\x12\x14\n" +
	"\x05price\x18\n" +
	" \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\v \x01(\tR\bquantity\x12\x1b\n" +
	"\tmaker_fee\x18\f \x01(\tR\bmakerFee\x12\x1b\n" +
	"\ttaker_fee\x18\r \x01(\tR\btakerFee\"\x18\n" +
	"\x16ApplySpotTradeResponse2\xd3\x02\n" +
	"\x06Wallet\x12D\n" +
	"\tGetAssets\x12\x1a.walletpb.GetAssetsRequest\x1a\x1b.walletpb.GetAssetsResponse\x12S\n" +
	"\x0eFreezeForOrder\x12\x1f.walletpb.FreezeForOrderRequest\x1a .walletpb.FreezeForOrderResponse\x12Y\n" +
	"\x10UnfreezeForOrder\x12!.walletpb.UnfreezeForOrderRequest\x1a\".walletpb.UnfreezeForOrderResponse\x12S\n" +
	"\x0eApplySpotTrade\x12\x1f.walletpb.ApplySpotTradeRequest\x1a .walletpb.ApplySpotTradeResponseB!Z\x1fbld-backend/api/wallet;walletpbb\x06proto3"

var (
	file_wallet_proto_rawDescOnce sync.Once
	file_wallet_proto_rawDescData []byte
)

func file_wallet_proto_rawDescGZIP() []byte {
	file_wallet_proto_rawDescOnce.Do(func() {
		file_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallet_proto_rawDesc), len(file_wallet_proto_rawDesc)))
	})
	return file_wallet_proto_rawDescData
}

var file_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_wallet_proto_goTypes = []any{
	(*GetAssetsRequest)(nil),         // 0: walletpb.GetAssetsRequest
	(*AssetItem)(nil),                // 1: walletpb.AssetItem
	(*GetAssetsResponse)(nil),        // 2: walletpb.GetAssetsResponse
	(*FreezeForOrderRequest)(nil),    // 3: walletpb.FreezeForOrderRequest
	(*FreezeForOrderResponse)(nil),   // 4: walletpb.FreezeForOrderResponse
	(*UnfreezeForOrderRequest)(nil),  // 5: walletpb.UnfreezeForOrderRequest
	(*UnfreezeForOrderResponse)(nil), // 6: walletpb.UnfreezeForOrderResponse
	(*ApplySpotTradeRequest)(nil),    // 7: walletpb.ApplySpotTradeRequest
	(*ApplySpotTradeResponse)(nil),   // 8: walletpb.ApplySpotTradeResponse
}
var file_wallet_proto_depIdxs = []int32{
	1, // 0: walletpb.GetAssetsResponse.items:type_name -> walletpb.AssetItem
	0, // 1: walletpb.Wallet.GetAssets:input_type -> walletpb.GetAssetsRequest
	3, // 2: walletpb.Wallet.FreezeForOrder:input_type -> walletpb.FreezeForOrderRequest
	5, // 3: walletpb.Wallet.UnfreezeForOrder:input_type -> walletpb.UnfreezeForOrderRequest
	7, // 4: walletpb.Wallet.ApplySpotTrade:input_type -> walletpb.ApplySpotTradeRequest
	2, // 5: walletpb.Wallet.GetAssets:output_type -> walletpb.GetAssetsResponse
	4, // 6: walletpb.Wallet.FreezeForOrder:output_type -> walletpb.FreezeForOrderResponse
	6, // 7: walletpb.Wallet.UnfreezeForOrder:output_type -> walletpb.UnfreezeForOrderResponse
	8, // 8: walletpb.Wallet.ApplySpotTrade:output_type -> walletpb.ApplySpotTradeResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wallet_proto_init() }
func file_wallet_proto_init() {
	if File_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_proto_rawDesc), len(file_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_proto_goTypes,
		DependencyIndexes: file_wallet_proto_depIdxs,
		MessageInfos:      file_wallet_proto_msgTypes,
	}.Build()
	File_wallet_proto = out.File
	file_wallet_proto_goTypes = nil
	file_wallet_proto_depIdxs = nil
}
