// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.6
// source: wallet.proto

package walletpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Wallet_GetAssets_FullMethodName        = "/walletpb.Wallet/GetAssets"
	Wallet_FreezeForOrder_FullMethodName   = "/walletpb.Wallet/FreezeForOrder"
	Wallet_UnfreezeForOrder_FullMethodName = "/walletpb.Wallet/UnfreezeForOrder"
	Wallet_ApplySpotTrade_FullMethodName   = "/walletpb.Wallet/ApplySpotTrade"
)

// WalletClient is the client API for Wallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Wallet：查询资产 + 供订单等服务 RPC 冻结/解冻余额。
type WalletClient interface {
	GetAssets(ctx context.Context, in *GetAssetsRequest, opts ...grpc.CallOption) (*GetAssetsResponse, error)
	// FreezeForOrder 将可用余额划入冻结，并写入 asset_freezes（同一 order_id+asset_id+trading_type 仅允许一条冻结中记录）。
	FreezeForOrder(ctx context.Context, in *FreezeForOrderRequest, opts ...grpc.CallOption) (*FreezeForOrderResponse, error)
	// UnfreezeForOrder 按订单+资产+交易类型解冻，将对应冻结金额退回可用。
	UnfreezeForOrder(ctx context.Context, in *UnfreezeForOrderRequest, opts ...grpc.CallOption) (*UnfreezeForOrderResponse, error)
	// ApplySpotTrade 现货成交同步结算：扣减双方冻结、增加可用、手续费、写 spot_fund_flows；trade_id 幂等。
	ApplySpotTrade(ctx context.Context, in *ApplySpotTradeRequest, opts ...grpc.CallOption) (*ApplySpotTradeResponse, error)
}

type walletClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletClient(cc grpc.ClientConnInterface) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) GetAssets(ctx context.Context, in *GetAssetsRequest, opts ...grpc.CallOption) (*GetAssetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssetsResponse)
	err := c.cc.Invoke(ctx, Wallet_GetAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) FreezeForOrder(ctx context.Context, in *FreezeForOrderRequest, opts ...grpc.CallOption) (*FreezeForOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FreezeForOrderResponse)
	err := c.cc.Invoke(ctx, Wallet_FreezeForOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) UnfreezeForOrder(ctx context.Context, in *UnfreezeForOrderRequest, opts ...grpc.CallOption) (*UnfreezeForOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfreezeForOrderResponse)
	err := c.cc.Invoke(ctx, Wallet_UnfreezeForOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) ApplySpotTrade(ctx context.Context, in *ApplySpotTradeRequest, opts ...grpc.CallOption) (*ApplySpotTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplySpotTradeResponse)
	err := c.cc.Invoke(ctx, Wallet_ApplySpotTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServer is the server API for Wallet service.
// All implementations must embed UnimplementedWalletServer
// for forward compatibility.
//
// Wallet：查询资产 + 供订单等服务 RPC 冻结/解冻余额。
type WalletServer interface {
	GetAssets(context.Context, *GetAssetsRequest) (*GetAssetsResponse, error)
	// FreezeForOrder 将可用余额划入冻结，并写入 asset_freezes（同一 order_id+asset_id+trading_type 仅允许一条冻结中记录）。
	FreezeForOrder(context.Context, *FreezeForOrderRequest) (*FreezeForOrderResponse, error)
	// UnfreezeForOrder 按订单+资产+交易类型解冻，将对应冻结金额退回可用。
	UnfreezeForOrder(context.Context, *UnfreezeForOrderRequest) (*UnfreezeForOrderResponse, error)
	// ApplySpotTrade 现货成交同步结算：扣减双方冻结、增加可用、手续费、写 spot_fund_flows；trade_id 幂等。
	ApplySpotTrade(context.Context, *ApplySpotTradeRequest) (*ApplySpotTradeResponse, error)
	mustEmbedUnimplementedWalletServer()
}

// UnimplementedWalletServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletServer struct{}

func (UnimplementedWalletServer) GetAssets(context.Context, *GetAssetsRequest) (*GetAssetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssets not implemented")
}
func (UnimplementedWalletServer) FreezeForOrder(context.Context, *FreezeForOrderRequest) (*FreezeForOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FreezeForOrder not implemented")
}
func (UnimplementedWalletServer) UnfreezeForOrder(context.Context, *UnfreezeForOrderRequest) (*UnfreezeForOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnfreezeForOrder not implemented")
}
func (UnimplementedWalletServer) ApplySpotTrade(context.Context, *ApplySpotTradeRequest) (*ApplySpotTradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplySpotTrade not implemented")
}
func (UnimplementedWalletServer) mustEmbedUnimplementedWalletServer() {}
func (UnimplementedWalletServer) testEmbeddedByValue()                {}

// UnsafeWalletServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServer will
// result in compilation errors.
type UnsafeWalletServer interface {
	mustEmbedUnimplementedWalletServer()
}

func RegisterWalletServer(s grpc.ServiceRegistrar, srv WalletServer) {
	// If the following call panics, it indicates UnimplementedWalletServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Wallet_ServiceDesc, srv)
}

func _Wallet_GetAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Wallet_GetAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetAssets(ctx, req.(*GetAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_FreezeForOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreezeForOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).FreezeForOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Wallet_FreezeForOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).FreezeForOrder(ctx, req.(*FreezeForOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_UnfreezeForOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfreezeForOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).UnfreezeForOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Wallet_UnfreezeForOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).UnfreezeForOrder(ctx, req.(*UnfreezeForOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_ApplySpotTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplySpotTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).ApplySpotTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Wallet_ApplySpotTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).ApplySpotTrade(ctx, req.(*ApplySpotTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Wallet_ServiceDesc is the grpc.ServiceDesc for Wallet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Wallet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "walletpb.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAssets",
			Handler:    _Wallet_GetAssets_Handler,
		},
		{
			MethodName: "FreezeForOrder",
			Handler:    _Wallet_FreezeForOrder_Handler,
		},
		{
			MethodName: "UnfreezeForOrder",
			Handler:    _Wallet_UnfreezeForOrder_Handler,
		},
		{
			MethodName: "ApplySpotTrade",
			Handler:    _Wallet_ApplySpotTrade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet.proto",
}
