// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateWalletReq struct {
	UserId uint64 `json:"user_id"`
}

type CreateWalletResp struct {
	WalletId uint64 `json:"wallet_id"`
	UserId   uint64 `json:"user_id"`
	Chain    string `json:"chain"`
	Address  string `json:"address"`
}

type HealthzResp struct {
	Status string `json:"status"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	UserId uint64 `json:"user_id"`
}

type GetDepositAddressReq struct {
	UserId uint64 `json:"user_id"`
	Symbol string `json:"symbol"`
}

type GetDepositAddressResp struct {
	WalletId        uint64 `json:"wallet_id"`
	Chain           string `json:"chain"`
	Address         string `json:"address"`
	Decimals        uint32 `json:"decimals"`
	ContractAddress string `json:"contract_address"`
}

type WithdrawReq struct {
	UserId      uint64 `json:"user_id"`
	Symbol      string `json:"symbol"`
	DestAddress string `json:"dest_address"`
	Amount      string `json:"amount"`
}

type WithdrawResp struct {
	WithdrawId uint64 `json:"withdraw_id"`
	TxHash     string `json:"tx_hash"`
	Status     string `json:"status"`
}

type SweepToHotReq struct {
	UserId uint64 `json:"user_id"`
	Symbol string `json:"symbol"`
	Amount string `json:"amount"`
}

type SweepToHotResp struct {
	TxHash       string `json:"tx_hash"`
	SweptAmount  string `json:"swept_amount"`
	Status       string `json:"status"`
}
